kbuild-dir := $(if $(filter /%,$(src)),$(src),$(srctree)/$(src))

subdir-ccflags-y += -I$(kbuild-dir)/include
subdir-ccflags-y += -I$(kbuild-dir)/../securemsm-kernel/include

include $(kbuild-dir)/config/auto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/autoconf.h

ifeq ($(CONFIG_BTFM_SWR),m)
KBUILD_CPPFLAGS += -DCONFIG_BTFM_SWR
endif

obj-$(CONFIG_MSM_BT_POWER) += pwr/
obj-$(CONFIG_BTFM_SLIM) += slimbus/
obj-$(CONFIG_I2C_RTC6226_QCA) += rtc6226/
obj-$(CONFIG_BTFM_CODEC) += btfmcodec/
obj-$(CONFIG_SLIM_BTFM_CODEC) += slimbus/
obj-$(CONFIG_BTFM_SWR) += soundwire/
