############ LPASS_CDC ############

# for LPASS_CDC Codec
ifdef CONFIG_SND_SOC_LPASS_CDC
	LPASS_CDC_OBJS += lpass-cdc.o
	LPASS_CDC_OBJS += lpass-cdc-comp.o
	LPASS_CDC_OBJS += lpass-cdc-utils.o
	LPASS_CDC_OBJS += lpass-cdc-regmap.o
	LPASS_CDC_OBJS += lpass-cdc-tables.o
	LPASS_CDC_OBJS += lpass-cdc-clk-rsc.o
endif

ifdef CONFIG_LPASS_CDC_WSA2_MACRO
	WSA2_OBJS += lpass-cdc-wsa2-macro.o
endif

ifdef CONFIG_LPASS_CDC_WSA_MACRO
	WSA_OBJS += lpass-cdc-wsa-macro.o
endif

ifdef CONFIG_LPASS_CDC_VA_MACRO
	VA_OBJS += lpass-cdc-va-macro.o
endif

ifdef CONFIG_LPASS_CDC_TX_MACRO
	TX_OBJS += lpass-cdc-tx-macro.o
endif

ifdef CONFIG_LPASS_CDC_RX_MACRO
	RX_OBJS += lpass-cdc-rx-macro.o
endif

# Module information used by KBuild framework
obj-$(CONFIG_SND_SOC_LPASS_CDC) += lpass_cdc_dlkm.o
lpass_cdc_dlkm-y := $(LPASS_CDC_OBJS)

obj-$(CONFIG_LPASS_CDC_WSA2_MACRO) += lpass_cdc_wsa2_macro_dlkm.o
lpass_cdc_wsa2_macro_dlkm-y := $(WSA2_OBJS)

obj-$(CONFIG_LPASS_CDC_WSA_MACRO) += lpass_cdc_wsa_macro_dlkm.o
lpass_cdc_wsa_macro_dlkm-y := $(WSA_OBJS)

obj-$(CONFIG_LPASS_CDC_VA_MACRO) += lpass_cdc_va_macro_dlkm.o
lpass_cdc_va_macro_dlkm-y := $(VA_OBJS)

obj-$(CONFIG_LPASS_CDC_TX_MACRO) += lpass_cdc_tx_macro_dlkm.o
lpass_cdc_tx_macro_dlkm-y := $(TX_OBJS)

obj-$(CONFIG_LPASS_CDC_RX_MACRO) += lpass_cdc_rx_macro_dlkm.o
lpass_cdc_rx_macro_dlkm-y := $(RX_OBJS)

# inject some build related information
DEFINES += -DBUILD_TIMESTAMP=\"$(shell date -u +'%Y-%m-%dT%H:%M:%SZ')\"
