############ WCD937X ############

# for WCD937X Codec
ifdef CONFIG_SND_SOC_WCD937X
	WCD937X_OBJS += wcd937x.o
	WCD937X_OBJS += wcd937x-regmap.o
	WCD937X_OBJS += wcd937x-tables.o
	WCD937X_OBJS += wcd937x-mbhc.o
endif

ifdef CONFIG_SND_SOC_WCD937X_SLAVE
	WCD937X_SLAVE_OBJS += wcd937x_slave.o
endif

# Module information used by KBuild framework
obj-$(CONFIG_SND_SOC_WCD937X) += wcd937x_dlkm.o
wcd937x_dlkm-y := $(WCD937X_OBJS)

obj-$(CONFIG_SND_SOC_WCD937X_SLAVE) += wcd937x_slave_dlkm.o
wcd937x_slave_dlkm-y := $(WCD937X_SLAVE_OBJS)

# inject some build related information
DEFINES += -DBUILD_TIMESTAMP=\"$(shell date -u +'%Y-%m-%dT%H:%M:%SZ')\"
