############ WSA884X ############

# for WSA884X Codec
ifdef CONFIG_SND_SOC_WSA884X
	WSA884X_OBJS += wsa884x.o
	WSA884X_OBJS += wsa884x-regmap.o
	WSA884X_OBJS += wsa884x-tables.o
endif

# Module information used by KBuild framework
obj-$(CONFIG_SND_SOC_WSA884X) += wsa884x_dlkm.o
wsa884x_dlkm-y := $(WSA884X_OBJS)
