############ WCD939X ############

# for WCD939X Codec
ifdef CONFIG_SND_SOC_WCD939X
	WCD939X_OBJS += wcd939x.o
	WCD939X_OBJS += wcd939x-regmap.o
	WCD939X_OBJS += wcd939x-tables.o
	WCD939X_OBJS += wcd939x-mbhc.o
endif

ifdef CONFIG_SND_SOC_WCD939X_SLAVE
	WCD939X_SLAVE_OBJS += wcd939x-slave.o
endif

# Module information used by KBuild framework
obj-$(CONFIG_SND_SOC_WCD939X) += wcd939x_dlkm.o
wcd939x_dlkm-y := $(WCD939X_OBJS)

obj-$(CONFIG_SND_SOC_WCD939X_SLAVE) += wcd939x_slave_dlkm.o
wcd939x_slave_dlkm-y := $(WCD939X_SLAVE_OBJS)
