############ EP92 ############

# for EP92 Codec
ifdef CONFIG_SND_SOC_EP92
	EP92_OBJS += ep92.o
endif

# Module information used by KBuild framework
obj-$(CONFIG_SND_SOC_EP92) += ep92_dlkm.o
ep92_dlkm-y := $(EP92_OBJS)
