############ CSRA66X0 ############

# for CSRA66X0 Codec
ifdef CONFIG_SND_SOC_CSRA66X0
	CSRA66X0_OBJS += csra66x0.o
endif

# Module information used by KBuild framework
obj-$(CONFIG_SND_SOC_CSRA66X0) += csra66x0_dlkm.o
csra66x0_dlkm-y := $(CSRA66X0_OBJS)
