kbuild-dir := $(if $(filter /%,$(src)),$(src),$(srctree)/$(src))

subdir-ccflags-y += -I$(kbuild-dir)/include/uapi/audio
subdir-ccflags-y += -I$(kbuild-dir)/include/asoc
subdir-ccflags-y += -I$(kbuild-dir)/include

BOARD_PLATFORM ?= $(CONFIG_BOARD_PLATFORM)

ifneq ($(CONFIG_ARCH_QTI_VM), y)
ifeq ($(BOARD_PLATFORM), pineapple)
include $(kbuild-dir)/config/pineappleauto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/pineappleautoconf.h
endif
ifeq ($(BOARD_PLATFORM), cliffs)
include $(kbuild-dir)/config/pineappleauto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/pineappleautoconf.h
endif
ifeq ($(BOARD_PLATFORM), volcano)
include $(kbuild-dir)/config/volcanoauto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/volcanoautoconf.h
endif
ifeq ($(CONFIG_ARCH_BENGAL), y)
include $(kbuild-dir)/config/bengalauto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/bengalautoconf.h
endif
ifeq ($(CONFIG_ARCH_KHAJE), y)
include $(kbuild-dir)/config/bengalauto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/bengalautoconf.h
endif
ifeq ($(CONFIG_QTI_QUIN_GVM), y)
include $(kbuild-dir)/config/gvmauto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/gvmautoconf.h
endif
ifeq ($(CONFIG_ARCH_HOLI), y)
include $(kbuild-dir)/config/holiauto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/holiautoconf.h
endif
ifeq ($(CONFIG_ARCH_BLAIR), y)
include $(kbuild-dir)/config/holiauto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/holiautoconf.h
endif
ifeq ($(CONFIG_ARCH_KALAMA), y)
include $(kbuild-dir)/config/kalamaauto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/kalamaautoconf.h
endif
ifeq ($(CONFIG_ARCH_KONA), y)
include $(kbuild-dir)/config/konaauto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/konaautoconf.h
endif
ifeq ($(CONFIG_ARCH_LAHAINA), y)
include $(kbuild-dir)/config/lahainaauto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/lahainaautoconf.h
endif
ifeq ($(CONFIG_ARCH_LITO), y)
include $(kbuild-dir)/config/litoauto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/litoautoconf.h
endif
ifeq ($(CONFIG_ARCH_PITTI), y)
include $(kbuild-dir)/config/pittiauto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/pittiautoconf.h
endif
ifeq ($(CONFIG_ARCH_QCS405), y)
include $(kbuild-dir)/config/qcs405auto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/qcs405autoconf.h
endif
ifeq ($(CONFIG_ARCH_SA6155), y)
include $(kbuild-dir)/config/sa6155auto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/sa6155autoconf.h
endif
ifeq ($(CONFIG_ARCH_SA7255), y)
include $(kbuild-dir)/config/sa7255auto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/sa7255autoconf.h
endif
ifeq ($(CONFIG_ARCH_SA8155), y)
include $(kbuild-dir)/config/sa8155auto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/sa8155autoconf.h
endif
ifeq ($(CONFIG_ARCH_SDXLEMUR), y)
include $(kbuild-dir)/config/sdxlemurauto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/sdxlemurautoconf.h
endif
ifeq ($(CONFIG_ARCH_SDXPOORWILLS), y)
include $(kbuild-dir)/config/sdxpoorwillsauto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/sdxpoorwillsautoconf.h
endif
ifeq ($(CONFIG_ARCH_SM6150), y)
include $(kbuild-dir)/config/sm6150auto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/sm6150autoconf.h
endif
ifeq ($(CONFIG_ARCH_SDMMAGPIE), y)
include $(kbuild-dir)/config/sm6150auto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/sm6150autoconf.h
endif
ifeq ($(CONFIG_ARCH_TRINKET), y)
include $(kbuild-dir)/config/sm6150auto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/sm6150autoconf.h
endif
ifeq ($(CONFIG_ARCH_SM8150), y)
include $(kbuild-dir)/config/sm8150auto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/sm8150autoconf.h
endif
ifeq ($(CONFIG_ARCH_SDMSHRIKE), y)
include $(kbuild-dir)/config/sm8150auto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/sm8150autoconf.h
endif
ifeq ($(CONFIG_ARCH_WAIPIO), y)
include $(kbuild-dir)/config/waipioauto.conf
subdir-ccflags-y += -include $(kbuild-dir)/config/waipioautoconf.h
endif
endif

obj-y := dsp/ ipc/ soc/ asoc/ asoc/codecs/ asoc/codecs/lpass-cdc/ asoc/codecs/bolero/ asoc/codecs/wcd939x/ asoc/codecs/wsa884x/ asoc/codecs/wcd938x/ asoc/codecs/wsa883x/ asoc/codecs/wcd937x/ asoc/codecs/wcd9378/
