############ WCD9378 ############

# for WCD9378 Codec
ifdef CONFIG_SND_SOC_WCD9378
	WCD9378_OBJS += wcd9378.o
	WCD9378_OBJS += wcd9378-regmap.o
	WCD9378_OBJS += wcd9378-tables.o
	WCD9378_OBJS += wcd9378-mbhc.o
endif

ifdef CONFIG_SND_SOC_WCD9378_SLAVE
	WCD9378_SLAVE_OBJS += wcd9378-slave.o
endif

# Module information used by KBuild framework
obj-$(CONFIG_SND_SOC_WCD9378) += wcd9378_dlkm.o
wcd9378_dlkm-y := $(WCD9378_OBJS)

obj-$(CONFIG_SND_SOC_WCD9378_SLAVE) += wcd9378_slave_dlkm.o
wcd9378_slave_dlkm-y := $(WCD9378_SLAVE_OBJS)

# inject some build related information
DEFINES += -DBUILD_TIMESTAMP=\"$(shell date -u +'%Y-%m-%dT%H:%M:%SZ')\"
