obj-m += rmnet_perf_tether.o
#Need core headers
ifneq ($(RMNET_CORE_INC_DIR),)
ccflags-y := -I$(RMNET_CORE_INC_DIR)
endif
ccflags-y += $(call cc-option,-Wno-misleading-indentation)
rmnet_perf_tether-y := rmnet_perf_tether_main.o
