# for AQT1000 Codec
ifeq ($(CONFIG_SND_SOC_AQT1000), m)
	AQT1000_CDC_OBJS += aqt1000-regmap.o
	AQT1000_CDC_OBJS += aqt1000-utils.o
	AQT1000_CDC_OBJS += aqt1000-core.o
	AQT1000_CDC_OBJS += aqt1000-irq.o
	AQT1000_CDC_OBJS += aqt1000-clsh.o
	AQT1000_CDC_OBJS += aqt1000.o
	AQT1000_CDC_OBJS += aqt1000-mbhc.o
endif

# Module information used by KBuild framework
obj-$(CONFIG_SND_SOC_AQT1000) += aqt1000_cdc_dlkm.o
aqt1000_cdc_dlkm-y := $(AQT1000_CDC_OBJS)
