############ BOLERO ############

# for BOLERO Codec
ifdef CONFIG_SND_SOC_BOLERO
	BOLERO_OBJS += bolero-cdc.o
	BOLERO_OBJS += bolero-cdc-utils.o
	BOLERO_OBJS += bolero-cdc-regmap.o
	BOLERO_OBJS += bolero-cdc-tables.o
	BOLERO_OBJS += bolero-clk-rsc.o
endif

ifdef CONFIG_WSA_MACRO
	WSA_OBJS += wsa-macro.o
endif

ifdef CONFIG_VA_MACRO
	VA_OBJS += va-macro.o
endif

ifdef CONFIG_TX_MACRO
	TX_OBJS += tx-macro.o
endif

ifdef CONFIG_RX_MACRO
	RX_OBJS += rx-macro.o
endif

# Module information used by KBuild framework
obj-$(CONFIG_SND_SOC_BOLERO) += bolero_cdc_dlkm.o
bolero_cdc_dlkm-y := $(BOLERO_OBJS)

obj-$(CONFIG_WSA_MACRO) += wsa_macro_dlkm.o
wsa_macro_dlkm-y := $(WSA_OBJS)

obj-$(CONFIG_VA_MACRO) += va_macro_dlkm.o
va_macro_dlkm-y := $(VA_OBJS)

obj-$(CONFIG_TX_MACRO) += tx_macro_dlkm.o
tx_macro_dlkm-y := $(TX_OBJS)

obj-$(CONFIG_RX_MACRO) += rx_macro_dlkm.o
rx_macro_dlkm-y := $(RX_OBJS)
