############ IPC ############

ifdef CONFIG_MSM_QDSP6_GPR_RPMSG
GPRV_GLINK += gpr-lite.o
endif

ifdef CONFIG_AUDIO_PKT
AUDIO_PKT += audio-pkt.o
endif

ifeq ($(CONFIG_SND_SOC_GCOV), y)
GCOV_PROFILE := y
endif

# Module information used by KBuild framework
obj-$(CONFIG_MSM_QDSP6_GPR_RPMSG) += gpr_dlkm.o
gpr_dlkm-y := $(GPRV_GLINK)

obj-$(CONFIG_AUDIO_PKT) += audio_pkt_dlkm.o
audio_pkt_dlkm-y := $(AUDIO_PKT)

# inject some build related information
CDEFINES += -DBUILD_TIMESTAMP=\"$(shell date -u +'%Y-%m-%dT%H:%M:%SZ')\"
