obj-m += rmnet_perf.o
#Need core headers
ifneq ($(RMNET_CORE_INC_DIR),)
ccflags-y := -I$(RMNET_CORE_INC_DIR)
endif
ccflags-y += $(call cc-option,-Wno-misleading-indentation)
rmnet_perf-y := rmnet_perf_main.o \
		rmnet_perf_tcp.o \
		rmnet_perf_udp.o
