obj-m += rmnet_aps.o
ifneq ($(RMNET_CORE_INC_DIR),)
ccflags-y := -I$(RMNET_CORE_INC_DIR)
endif
ccflags-y += $(call cc-option,-Wno-misleading-indentation)
rmnet_aps-y := \
        rmnet_aps_main.o \
	rmnet_aps_genl.o
