############ QDSP6V2 ############

ifdef CONFIG_SND_SOC_MSM_QDSP6V2_INTF
	Q6_OBJS += msm-audio-event-notify.o
	Q6_OBJS += q6_init.o
endif

ifdef CONFIG_SND_SOC_MSM_QDSP6V2_VM
	Q6_OBJS += msm-audio-event-notify.o
	Q6_OBJS += msm_audio_ion_vm.o
	Q6_OBJS += q6_init.o
endif

ifdef CONFIG_MSM_AVTIMER
	Q6_OBJS += avtimer.o
endif

ifdef CONFIG_XT_LOGGING
	Q6_OBJS += sp_params.o
endif

ifdef CONFIG_MSM_ADSP_LOADER
ADSP_LOADER_OBJS += adsp-loader.o
endif

ifdef CONFIG_MSM_QDSP6_PDR
QDSP6_PDR_OBJS += audio_pdr.o
endif

ifdef CONFIG_MSM_QDSP6_NOTIFIER
QDSP6_NOTIFIER_OBJS += audio_notifier.o audio_ssr.o
endif

ifdef CONFIG_SPF_CORE
SPF_CORE_OBJS += spf-core.o
endif

ifdef CONFIG_AUDIO_PRM
AUDIO_PRM += audio_prm.o
endif

ifdef CONFIG_AUDIO_PKT_ION
AUDIO_PKT_ION += msm_audio_ion.o
endif

ifdef CONFIG_VOICE_MHI
VOICE_MHI += voice_mhi.o
endif

ifdef CONFIG_DIGITAL_CDC_RSC_MGR
	SPF_CORE_OBJS += digital-cdc-rsc-mgr.o
endif

obj-$(CONFIG_SND_SOC_MSM_QDSP6V2_INTF) += q6_dlkm.o
q6_dlkm-y := $(Q6_OBJS)

obj-$(CONFIG_SND_SOC_MSM_QDSP6V2_VM) += q6_dlkm.o
q6_dlkm-y := $(Q6_OBJS)

obj-$(CONFIG_MSM_ADSP_LOADER) += adsp_loader_dlkm.o
adsp_loader_dlkm-y := $(ADSP_LOADER_OBJS)

obj-$(CONFIG_MSM_QDSP6_PDR) += q6_pdr_dlkm.o
q6_pdr_dlkm-y := $(QDSP6_PDR_OBJS)

obj-$(CONFIG_SPF_CORE) += spf_core_dlkm.o
spf_core_dlkm-y := $(SPF_CORE_OBJS)

obj-$(CONFIG_MSM_QDSP6_NOTIFIER) += q6_notifier_dlkm.o
q6_notifier_dlkm-y := $(QDSP6_NOTIFIER_OBJS)

obj-$(CONFIG_AUDIO_PRM) += audio_prm_dlkm.o
audio_prm_dlkm-y := $(AUDIO_PRM)

obj-$(CONFIG_AUDIO_PKT_ION) += audpkt_ion_dlkm.o
audpkt_ion_dlkm-y := $(AUDIO_PKT_ION)

obj-$(CONFIG_VOICE_MHI) += voice_mhi_dlkm.o
voice_mhi_dlkm-y := $(VOICE_MHI)

# inject some build related information
DEFINES += -DBUILD_TIMESTAMP=\"$(shell date -u +'%Y-%m-%dT%H:%M:%SZ')\"
