# SPDX-License-Identifier: GPL-2.0-only
kbuild-dir := $(if $(filter /%,$(src)),$(src),$(srctree)/$(src))
DATAIPADRVTOP = $(kbuild-dir)
subdir-ccflags-y += -DGSI_TRACE_INCLUDE_PATH=$(kbuild-dir)/gsi
subdir-ccflags-y += -DIPA_TRACE_INCLUDE_PATH=$(kbuild-dir)/ipa/ipa_v3
subdir-ccflags-y += -DRNDIS_TRACE_INCLUDE_PATH=$(kbuild-dir)/ipa/ipa_clients
ifeq ($(CONFIG_ARCH_NIOBE), y)
subdir-ccflags-y += -DCONFIG_IPA_RTP
subdir-ccflags-y += -I$(kbuild-dir)/../../../../synx-kernel/include/uapi/synx/media
subdir-ccflags-y += -I$(kbuild-dir)/../../../../synx-kernel/msm/synx
else
subdir-ccflags-y += -DCONFIG_IPA_RMNET_MEM
subdir-ccflags-y += -I$(kbuild-dir)/../../../../datarmnet-ext/mem
endif

#MSMs - GKI
ifeq ($(CONFIG_ARCH_LAHAINA), y)
LINUXINCLUDE    += -include $(kbuild-dir)/../../../config/dataipa.h
ifeq ($(CONFIG_QGKI),y)
include $(kbuild-dir)/../../../config/dataipa_QGKI.conf
ifeq ($(CONFIG_LOCALVERSION), "-qgki-debug")
include $(kbuild-dir)/../../../config/dataipa_debug.conf
LINUXINCLUDE    += -include $(kbuild-dir)/../../../config/dataipa_debug.h
endif
else
include $(kbuild-dir)/../../../config/dataipa_GKI.conf
endif
endif

#MSM - Vendor SI
ifeq ($(filter $(CONFIG_ARCH_WAIPIO) $(CONFIG_ARCH_KALAMA) $(CONFIG_ARCH_PINEAPPLE) $(CONFIG_ARCH_CLIFFS) $(CONFIG_ARCH_PITTI) $(CONFIG_ARCH_VOLCANO), y),y)
LINUXINCLUDE    += -include $(kbuild-dir)/../../../config/dataipa_vendor.h
include $(kbuild-dir)/../../../config/dataipa_GKI.conf
ifeq ($(CONFIG_LOCALVERSION), "-gki-consolidate")
include $(kbuild-dir)/../../../config/dataipa_GKI_consolidate.conf
LINUXINCLUDE    += -include $(kbuild-dir)/../../../config/dataipa_debug.h
endif
endif

ifeq ($(filter $(CONFIG_ARCH_KHAJE) $(CONFIG_ARCH_BLAIR) $(CONFIG_ARCH_HOLI) $(CONFIG_ARCH_MONACO), y), y)
LINUXINCLUDE    += -include $(kbuild-dir)/../../../config/dataipa_vendor_ipav4.h
include $(kbuild-dir)/../../../config/dataipa_GKI_ipav4.conf
ifeq ($(CONFIG_LOCALVERSION), "-gki-consolidate")
include $(kbuild-dir)/../../../config/dataipa_GKI_consolidate.conf
LINUXINCLUDE    += -include $(kbuild-dir)/../../../config/dataipa_debug.h
endif
endif

#MDMs
ifeq ($(CONFIG_ARCH_SDXLEMUR), y)
LINUXINCLUDE    += -include $(kbuild-dir)/../../../config/dataipa.h
include $(kbuild-dir)/../../../config/dataipa_QGKI.conf
ifneq ($(CONFIG_LOCALVERSION), "-perf")
include $(kbuild-dir)/../../../config/dataipa_debug.conf
LINUXINCLUDE    += -include $(kbuild-dir)/../../../config/dataipa_debug.h
endif
endif

ifeq ($(CONFIG_ARCH_SDXNIGHTJAR), y)
LINUXINCLUDE    += -include $(kbuild-dir)/../../../config/sdx12dataipa.h
include $(kbuild-dir)/../../../config/sdx12dataipa_QGKI.conf
ifneq ($(CONFIG_LOCALVERSION), "-perf")
include $(kbuild-dir)/../../../config/dataipa_debug.conf
LINUXINCLUDE    += -include $(kbuild-dir)/../../../config/dataipa_debug.h
endif
endif

ifeq ($(CONFIG_ARCH_SCUBA), y)
LINUXINCLUDE    += -include $(kbuild-dir)/../../../config/sa410mdataipa.h
include $(kbuild-dir)/../../../config/sa410mdataipa_QGKI.conf
ifneq ($(CONFIG_LOCALVERSION), "-perf")
include $(kbuild-dir)/../../../config/dataipa_debug.conf
LINUXINCLUDE    += -include $(kbuild-dir)/../../../config/dataipa_debug.h
endif
endif

ifneq (,$(filter $(CONFIG_IPA3) $(CONFIG_GSI),y m))
LINUXINCLUDE += -I$(DATAIPADRVTOP)/include
LINUXINCLUDE += -I$(DATAIPADRVTOP)/include/linux
LINUXINCLUDE += -I$(DATAIPADRVTOP)/include/uapi
LINUXINCLUDE += -I$(DATAIPADRVTOP)/gsi
LINUXINCLUDE += -I$(DATAIPADRVTOP)/gsi/gsihal
LINUXINCLUDE += -I$(DATAIPADRVTOP)/ipa
LINUXINCLUDE += -I$(DATAIPADRVTOP)/ipa/ipa_v3
LINUXINCLUDE += -I$(DATAIPADRVTOP)/ipa/ipa_v3/ipahal
LINUXINCLUDE += -I$(DATAIPADRVTOP)/ipa/ipa_clients
ifneq (,$(filter $(CONFIG_IPA_KERNEL_TESTS_MODULE),y m))
LINUXINCLUDE += -I$(DATAIPADRVTOP)/ipa/ipa_test_module
endif
endif

ifneq (,$(filter $(CONFIG_IPA3_REGDUMP),y m))
LINUXINCLUDE += -I$(DATAIPADRVTOP)/ipa/ipa_v3/dump
endif

ifneq (,$(filter $(CONFIG_IPA3_REGDUMP_IPA_4_5),y m))
LINUXINCLUDE += -I$(DATAIPADRVTOP)/ipa/ipa_v3/dump/ipa4.5
endif

ifneq (,$(filter $(CONFIG_IPA3_REGDUMP_IPA_5_0),y m))
LINUXINCLUDE += -I$(DATAIPADRVTOP)/ipa/ipa_v3/dump/ipa5.0
endif

ifneq (,$(filter $(CONFIG_IPA3_REGDUMP_IPA_5_5),y m))
LINUXINCLUDE += -I$(DATAIPADRVTOP)/ipa/ipa_v3/dump/ipa5.5
endif


obj-$(CONFIG_GSI) += gsi/
obj-$(CONFIG_IPA3) += ipa/
