############ ROULEUR ############

# for ROULEUR Codec
ifdef CONFIG_SND_SOC_ROULEUR
	ROULEUR_OBJS += rouleur.o
	ROULEUR_OBJS += rouleur-regmap.o
	ROULEUR_OBJS += rouleur-tables.o
	ROULEUR_OBJS += rouleur-mbhc.o
endif

ifdef CONFIG_PM2250_SPMI
	PM2250_SPMI_OBJS += pm2250_spmi.o
endif

ifdef CONFIG_SND_SOC_ROULEUR_SLAVE
	ROULEUR_SLAVE_OBJS += rouleur_slave.o
endif

# Module information used by KBuild framework
obj-$(CONFIG_SND_SOC_ROULEUR) += rouleur_dlkm.o
rouleur_dlkm-y := $(ROULEUR_OBJS)

obj-$(CONFIG_SND_SOC_ROULEUR_SLAVE) += rouleur_slave_dlkm.o
rouleur_slave_dlkm-y := $(ROULEUR_SLAVE_OBJS)

obj-$(CONFIG_PM2250_SPMI) += pm2250_spmi_dlkm.o
pm2250_spmi_dlkm-y := $(PM2250_SPMI_OBJS)

# inject some build related information
DEFINES += -DBUILD_TIMESTAMP=\"$(shell date -u +'%Y-%m-%dT%H:%M:%SZ')\"
